[tox]
envlist =
    {py310,py311,py312,py313}-django{42,50,51}

[testenv]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/django_password_history
commands = coverage run --source django_password_history runtests.py
deps =
    django42: Django>=4.2,<5.0
    django50: Django>=5.0,<5.1
    django51: Django>=5.1,<6.0
    -r{toxinidir}/requirements_test.txt
basepython =
    py313: python3.13
    py312: python3.12
    py311: python3.11
    py310: python3.10